import { useEffect, useRef, useState } from "react";
import {
  animate,
  motion,
  useMotionValue,
  useTransform,
  type MotionValue,
  type PanInfo,
} from "motion/react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

type Section = { label: string; render: () => React.ReactNode };

const SECTIONS: Section[] = [
  {
    label: "Today",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">
          Syra <span>→</span> Daily Brief <span>·</span> Just now
        </div>
        <div className="db-greeting">Good morning, John.</div>
        <p className="db-lede">
          Markets opened steady. Hartley Trust review is your priority, followed by the Marlow
          rebalance at 11:30.
        </p>
        <SectionRule label="Priorities" />
        <div className="flex-1">
          <PRow
            tone="hi"
            name="Hartley Family Trust — IPS sign-off"
            detail="Olivia's draft ready. Review before 9am."
            time="9:00 – 10:00 AM"
          />
          <PRow
            tone="hi"
            name="Denis Marlow — portfolio rebalance"
            detail="Allocation memo attached. Cleared to proceed."
            time="11:30 AM"
          />
          <PRow
            tone="mid"
            name="Office B123 onboarding prep"
            detail="No owner assigned."
            time="Due Friday"
          />
        </div>
      </div>
    ),
  },
  {
    label: "Reminders & Markets",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">Action items · Market open</div>
        <div className="db-greeting db-greeting--sm">Three things before noon.</div>
        <SectionRule label="Reminders" />
        <div className="mb-6">
          <Rem text="Review Hartley Q4 statements" when="Due now" />
          <Rem text="Reply to Olivia — confirm IPS call Thursday 2pm" when="Draft queued" />
          <Rem text="Review Marlow allocation memo" when="Before 11:30" />
        </div>
        <SectionRule label="Markets" />
        <div className="grid grid-cols-2 gap-x-3 gap-y-4">
          <Mkt ticker="10-yr Treasury" val="4.31%" delta="▼ 6bps" tone="dn" />
          <Mkt ticker="S&P 500" val="Flat" delta="+0.02%" tone="flat" />
          <Mkt ticker="Breadth" val={<span className="text-status-success">Improved</span>} />
          <Mkt
            ticker="Fed speakers"
            val={<span className="text-[14px] text-muted-foreground font-light">None today</span>}
          />
        </div>
      </div>
    ),
  },
  {
    label: "News digest",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">Context · Curated by Syra</div>
        <div className="db-greeting db-greeting--sm">What's moving today.</div>
        <blockquote className="border-l-2 border-status-info py-2 px-3.5 mb-5">
          <p className="font-serif-display text-[13px] italic text-muted-foreground leading-[1.6]">
            "Advancers outpaced decliners across all sectors. Treasuries firmed on softer CPI
            revisions."
          </p>
        </blockquote>
        <SectionRule label="News digest" />
        <div className="flex-1">
          <News
            src="Financial Times"
            hed="Treasury yields slip as CPI revision points to cooler inflation"
            body="Bond-heavy portfolios may benefit — relevant for Hartley and Marlow."
          />
          <News
            src="WSJ"
            hed="Wealth managers face tighter fiduciary disclosure rules in Q3"
            body="SEC guidance takes effect July 1. Review IPS docs before deadline."
          />
          <News
            src="Bloomberg"
            hed="Private credit spreads tighten as institutional demand surges"
            body="Inflows not seen since 2021. Context for alternatives exposure."
          />
        </div>
        <div className="mt-4 pt-3 border-t border-border/40 text-[10px] text-muted-foreground/50 tracking-wide">
          Generated by Syra · Harwick &amp; Sterne · Confidential · Jun 9, 2026
        </div>
      </div>
    ),
  },
];

function SectionRule({ label }: { label: string }) {
  return (
    <div className="flex items-center gap-2 mb-2.5 mt-1">
      <span className="text-[9px] tracking-[0.2em] uppercase text-muted-foreground whitespace-nowrap font-medium">
        {label}
      </span>
      <div className="flex-1 h-px bg-border/60" />
    </div>
  );
}

function PRow({
  tone,
  name,
  detail,
  time,
}: {
  tone: "hi" | "mid" | "ok";
  name: string;
  detail: string;
  time?: string;
}) {
  const dot =
    tone === "hi" ? "bg-status-info" : tone === "mid" ? "bg-muted-foreground" : "bg-border";
  return (
    <div className="flex gap-3 py-3 border-b border-border/40 last:border-b-0">
      <div className={cn("w-[7px] h-[7px] rounded-full mt-1.5 shrink-0", dot)} />
      <div className="min-w-0 flex-1">
        <div className="text-[14px] font-medium text-surface-foreground leading-snug">{name}</div>
        <div className="text-[12.5px] font-light text-muted-foreground leading-[1.5] mt-0.5">
          {detail}
        </div>
        {time && <div className="text-[11px] text-muted-foreground mt-1">{time}</div>}
      </div>
    </div>
  );
}

function Rem({ text, when }: { text: string; when: string }) {
  return (
    <div className="flex items-start gap-3 py-2.5 border-b border-border/40 last:border-b-0">
      <div className="w-[16px] h-[16px] rounded border border-border shrink-0 mt-px" />
      <div className="min-w-0 flex-1">
        <div className="text-[13.5px] text-surface-foreground leading-snug">{text}</div>
        <div className="text-[11px] text-muted-foreground mt-0.5">{when}</div>
      </div>
    </div>
  );
}

function Mkt({
  ticker,
  val,
  delta,
  tone,
}: {
  ticker: string;
  val: React.ReactNode;
  delta?: string;
  tone?: "up" | "dn" | "flat";
}) {
  const tc =
    tone === "up"
      ? "text-status-success"
      : tone === "dn"
        ? "text-status-danger"
        : "text-muted-foreground";
  return (
    <div>
      <div className="text-[9px] tracking-[0.1em] uppercase text-muted-foreground mb-1">
        {ticker}
      </div>
      <div className="text-[15px] font-medium text-surface-foreground">
        {val} {delta && <span className={cn("text-[11px] ml-1 font-normal", tc)}>{delta}</span>}
      </div>
    </div>
  );
}

function News({ src, hed, body }: { src: string; hed: string; body: string }) {
  return (
    <div className="py-3 border-b border-border/40 last:border-b-0">
      <div className="text-[9px] tracking-[0.12em] uppercase text-muted-foreground mb-1">{src}</div>
      <div className="text-[13.5px] font-medium text-surface-foreground leading-snug mb-0.5">
        {hed}
      </div>
      <div className="text-[12px] font-light text-muted-foreground leading-[1.5]">{body}</div>
    </div>
  );
}

function SwipeCard({
  section,
  offset,
  hidden,
  isPrevious,
  isTop,
  stackDragX,
  onDragMotion,
  onSwipeIntent,
  onSwipeComplete,
  total,
}: {
  section: Section;
  offset: number;
  hidden: boolean;
  isPrevious: boolean;
  isTop: boolean;
  stackDragX: MotionValue<number>;
  onDragMotion: (x: number) => void;
  onSwipeIntent: (dir: 1 | -1) => boolean;
  onSwipeComplete: (dir: 1 | -1) => void;
  total: number;
}) {
  const x = useMotionValue(0);
  const isThrowing = useRef(false);
  const rotate = useTransform(x, [-360, 0, 360], [-15, 0, 15]);
  const opacity = useTransform(x, [-620, -260, 0, 260, 620], [0, 1, 1, 1, 0]);
  const previousOpacity = useTransform(stackDragX, [0, 48, 170], [0, 0.7, 1]);
  const previousScale = useTransform(stackDragX, [0, 170], [0.955, 1]);
  const previousY = useTransform(stackDragX, [0, 170], [16, 0]);
  const nextScale = useTransform(stackDragX, [-170, 0], [1, 0.955]);
  const nextY = useTransform(stackDragX, [-170, 0], [0, 15]);

  const stackStyle = isTop
    ? { x, rotate, opacity, zIndex: total + 3 }
    : isPrevious
      ? { opacity: previousOpacity, scale: previousScale, y: previousY, zIndex: total + 2 }
      : offset === 1 && !hidden
        ? { scale: nextScale, y: nextY, zIndex: total - offset }
        : { zIndex: total - offset };

  useEffect(() => {
    if (isTop && !isThrowing.current) x.set(0);
  }, [isTop, x]);

  const handleDragEnd = (_: unknown, info: PanInfo) => {
    if (isThrowing.current) return;

    const dir: 1 | -1 = info.offset.x < 0 ? 1 : -1;
    const shouldThrow = Math.abs(info.offset.x) > 104 || Math.abs(info.velocity.x) > 520;

    if (!shouldThrow || !onSwipeIntent(dir)) {
      onDragMotion(0);
      animate(x, 0, { type: "spring", stiffness: 520, damping: 38, mass: 0.55 });
      return;
    }

    isThrowing.current = true;
    animate(stackDragX, dir === 1 ? -170 : 170, {
      duration: 0.34,
      ease: [0.2, 0.82, 0.24, 1],
    });
    animate(x, dir === 1 ? -680 : 680, {
      duration: 0.34,
      ease: [0.2, 0.82, 0.24, 1],
    }).then(() => {
      onSwipeComplete(dir);
      stackDragX.set(0);
      x.set(0);
      isThrowing.current = false;
    });
  };

  return (
    <motion.div
      className="absolute inset-0"
      style={stackStyle}
      initial={false}
      animate={{
        scale: isTop || isPrevious || offset === 1 ? undefined : hidden ? 0.94 : 1 - offset * 0.045,
        y: isTop || isPrevious || offset === 1 ? undefined : hidden ? 24 : offset * 15,
        opacity: isTop || isPrevious ? undefined : hidden || offset > 2 ? 0 : 1,
      }}
      transition={{ type: "spring", stiffness: 360, damping: 34, mass: 0.72 }}
      drag={isTop ? "x" : false}
      dragElastic={0.18}
      dragMomentum={false}
      onDrag={isTop ? (_, info) => onDragMotion(info.offset.x) : undefined}
      onDragEnd={isTop ? handleDragEnd : undefined}
    >
      <div className="h-full w-full bg-surface rounded-[24px] border border-border shadow-popover px-7 pt-7 pb-6 overflow-hidden cursor-grab active:cursor-grabbing">
        {section.render()}
      </div>
    </motion.div>
  );
}

export function DailyBriefStack({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (o: boolean) => void;
}) {
  const [index, setIndex] = useState(0);
  const [closingAfterSwipe, setClosingAfterSwipe] = useState(false);
  const stackDragX = useMotionValue(0);
  const total = SECTIONS.length;

  const handleSwipeIntent = (dir: 1 | -1) => {
    if (dir === -1 && index === 0) return false;
    if (dir === 1 && index === total - 1) setClosingAfterSwipe(true);
    return true;
  };

  const handleSwipeComplete = (dir: 1 | -1) => {
    setIndex((i) => {
      if (dir === 1 && i >= total - 1) {
        // Advance past the end so the just-thrown card is no longer the
        // top card (hidden=true) — prevents it snapping back to center
        // when SwipeCard resets x to 0 while the dialog closes.
        window.setTimeout(() => onOpenChange(false), 80);
        window.setTimeout(() => {
          setIndex(0);
          setClosingAfterSwipe(false);
          stackDragX.set(0);
        }, 280);
        return i + 1;
      }
      return Math.max(0, Math.min(total - 1, i + dir));
    });
  };

  const handleOpenChange = (o: boolean) => {
    onOpenChange(o);
    if (!o) {
      window.setTimeout(() => {
        setIndex(0);
        setClosingAfterSwipe(false);
        stackDragX.set(0);
      }, 180);
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-[440px] p-0 bg-transparent border-0 shadow-none [&>button]:hidden">
        <DialogTitle className="sr-only">Daily brief</DialogTitle>
        <div className="relative h-[620px] w-full select-none">
          {SECTIONS.map((section, i) => {
            if (i > index + 2) return null;
            return (
              <SwipeCard
                key={i}
                section={section}
                offset={Math.max(0, i - index)}
                hidden={i < index}
                isPrevious={i === index - 1}
                isTop={i === index}
                stackDragX={stackDragX}
                onDragMotion={(value) => stackDragX.set(value)}
                onSwipeIntent={handleSwipeIntent}
                onSwipeComplete={handleSwipeComplete}
                total={total}
              />
            );
          })}
        </div>

        {!closingAfterSwipe && (
          <div className="flex justify-center gap-1.5 mt-5">
            {SECTIONS.map((_, i) => (
              <button
                key={i}
                type="button"
                onClick={() => {
                  setClosingAfterSwipe(false);
                  setIndex(i);
                }}
                className={cn(
                  "h-1.5 rounded-full transition-all",
                  i === index
                    ? "w-7 bg-primary-foreground"
                    : "w-1.5 bg-primary-foreground/35 hover:bg-primary-foreground/55",
                )}
                aria-label={`Go to ${SECTIONS[i].label}`}
              />
            ))}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

const _styles = `
.db-eyebrow { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted-foreground); margin-bottom: 14px; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
.db-eyebrow span { color: var(--muted-foreground); }
.db-greeting { font-family: var(--font-serif-display, 'Playfair Display', serif); font-size: 30px; font-weight: 400; line-height: 1.1; color: var(--surface-foreground); margin-bottom: 10px; letter-spacing: 0; }
.db-greeting--sm { font-size: 24px; }
.db-lede { font-size: 14px; font-weight: 300; color: var(--muted-foreground); line-height: 1.6; margin-bottom: 22px; }
`;
if (typeof document !== "undefined" && !document.getElementById("db-stack-styles")) {
  const el = document.createElement("style");
  el.id = "db-stack-styles";
  el.textContent = _styles;
  document.head.appendChild(el);
}
