import { useState } from "react";
import { motion, AnimatePresence, useMotionValue, useTransform, type PanInfo } from "motion/react";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

type Section = { label: string; render: () => React.ReactNode };

const SECTIONS: Section[] = [
  {
    label: "Today",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">
          Syra <span>→</span> Daily Brief <span>·</span> Just now
        </div>
        <div className="db-greeting">Good morning, John.</div>
        <p className="db-lede">
          Markets opened steady. Hartley Trust review is your priority, followed by the
          Marlow rebalance at 11:30.
        </p>
        <SectionRule label="Priorities" />
        <div className="flex-1">
          <PRow tone="hi" name="Hartley Family Trust — IPS sign-off" detail="Olivia's draft ready. Review before 9am." time="9:00 – 10:00 AM" />
          <PRow tone="hi" name="Denis Marlow — portfolio rebalance" detail="Allocation memo attached. Cleared to proceed." time="11:30 AM" />
          <PRow tone="mid" name="Office B123 onboarding prep" detail="No owner assigned." time="Due Friday" />
        </div>
      </div>
    ),
  },
  {
    label: "Reminders & Markets",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">Action items · Market open</div>
        <div className="db-greeting db-greeting--sm">Three things before noon.</div>
        <SectionRule label="Reminders" />
        <div className="mb-6">
          <Rem text="Review Hartley Q4 statements" when="Due now" />
          <Rem text="Reply to Olivia — confirm IPS call Thursday 2pm" when="Draft queued" />
          <Rem text="Review Marlow allocation memo" when="Before 11:30" />
        </div>
        <SectionRule label="Markets" />
        <div className="grid grid-cols-2 gap-x-3 gap-y-4">
          <Mkt ticker="10-yr Treasury" val="4.31%" delta="▼ 6bps" tone="dn" />
          <Mkt ticker="S&P 500" val="Flat" delta="+0.02%" tone="flat" />
          <Mkt ticker="Breadth" val={<span className="text-[#3B6D11]">Improved</span>} />
          <Mkt ticker="Fed speakers" val={<span className="text-[14px] text-neutral-400 font-light">None today</span>} />
        </div>
      </div>
    ),
  },
  {
    label: "News digest",
    render: () => (
      <div className="flex h-full flex-col">
        <div className="db-eyebrow">Context · Curated by Syra</div>
        <div className="db-greeting db-greeting--sm">What's moving today.</div>
        <blockquote className="border-l-2 border-[#7F77DD] py-2 px-3.5 mb-5">
          <p className="font-serif-display text-[13px] italic text-neutral-500 leading-[1.6]">
            "Advancers outpaced decliners across all sectors. Treasuries firmed on softer CPI revisions."
          </p>
        </blockquote>
        <SectionRule label="News digest" />
        <div className="flex-1">
          <News src="Financial Times" hed="Treasury yields slip as CPI revision points to cooler inflation" body="Bond-heavy portfolios may benefit — relevant for Hartley and Marlow." />
          <News src="WSJ" hed="Wealth managers face tighter fiduciary disclosure rules in Q3" body="SEC guidance takes effect July 1. Review IPS docs before deadline." />
          <News src="Bloomberg" hed="Private credit spreads tighten as institutional demand surges" body="Inflows not seen since 2021. Context for alternatives exposure." />
        </div>
        <div className="mt-4 pt-3 border-t border-[#f0f0f0] text-[10px] text-neutral-300 tracking-wide">
          Generated by Syra · Harwick &amp; Sterne · Confidential · Jun 9, 2026
        </div>
      </div>
    ),
  },
];

function SectionRule({ label }: { label: string }) {
  return (
    <div className="flex items-center gap-2 mb-2.5 mt-1">
      <span className="text-[9px] tracking-[0.2em] uppercase text-neutral-400 whitespace-nowrap font-medium">
        {label}
      </span>
      <div className="flex-1 h-px bg-[#ececec]" />
    </div>
  );
}

function PRow({ tone, name, detail, time }: { tone: "hi" | "mid" | "ok"; name: string; detail: string; time?: string }) {
  const dot = tone === "hi" ? "bg-[#7F77DD]" : tone === "mid" ? "bg-[#ccc]" : "bg-[#e2e2e2]";
  return (
    <div className="flex gap-3 py-3 border-b border-[#f4f4f4] last:border-b-0">
      <div className={cn("w-[7px] h-[7px] rounded-full mt-1.5 shrink-0", dot)} />
      <div className="min-w-0 flex-1">
        <div className="text-[14px] font-medium text-neutral-900 leading-snug">{name}</div>
        <div className="text-[12.5px] font-light text-neutral-500 leading-[1.5] mt-0.5">{detail}</div>
        {time && <div className="text-[11px] text-neutral-400 mt-1">{time}</div>}
      </div>
    </div>
  );
}

function Rem({ text, when }: { text: string; when: string }) {
  return (
    <div className="flex items-start gap-3 py-2.5 border-b border-[#f4f4f4] last:border-b-0">
      <div className="w-[16px] h-[16px] rounded border border-[#ddd] shrink-0 mt-px" />
      <div className="min-w-0 flex-1">
        <div className="text-[13.5px] text-neutral-700 leading-snug">{text}</div>
        <div className="text-[11px] text-neutral-400 mt-0.5">{when}</div>
      </div>
    </div>
  );
}

function Mkt({ ticker, val, delta, tone }: { ticker: string; val: React.ReactNode; delta?: string; tone?: "up" | "dn" | "flat" }) {
  const tc = tone === "up" ? "text-[#3B6D11]" : tone === "dn" ? "text-[#A32D2D]" : "text-neutral-400";
  return (
    <div>
      <div className="text-[9px] tracking-[0.1em] uppercase text-neutral-400 mb-1">{ticker}</div>
      <div className="text-[15px] font-medium text-neutral-900">
        {val} {delta && <span className={cn("text-[11px] ml-1 font-normal", tc)}>{delta}</span>}
      </div>
    </div>
  );
}

function News({ src, hed, body }: { src: string; hed: string; body: string }) {
  return (
    <div className="py-3 border-b border-[#f4f4f4] last:border-b-0">
      <div className="text-[9px] tracking-[0.12em] uppercase text-neutral-400 mb-1">{src}</div>
      <div className="text-[13.5px] font-medium text-neutral-900 leading-snug mb-0.5">{hed}</div>
      <div className="text-[12px] font-light text-neutral-500 leading-[1.5]">{body}</div>
    </div>
  );
}

function SwipeCard({
  section,
  offset,
  isTop,
  onSwipe,
  total,
  exitDirection,
}: {
  section: Section;
  offset: number;
  isTop: boolean;
  onSwipe: (dir: 1 | -1) => void;
  total: number;
  exitDirection: 1 | -1;
}) {
  const x = useMotionValue(0);
  const rotate = useTransform(x, [-320, 0, 320], [-14, 0, 14]);
  const opacity = useTransform(x, [-360, -170, 0, 170, 360], [0.18, 1, 1, 1, 0.18]);

  const handleDragEnd = (_: unknown, info: PanInfo) => {
    const swipe = Math.abs(info.offset.x) * info.velocity.x;
    if (swipe < -10000 || info.offset.x < -140) onSwipe(1);
    else if (swipe > 10000 || info.offset.x > 140) onSwipe(-1);
  };

  return (
    <motion.div
      className="absolute inset-0"
      style={isTop ? { x, rotate, opacity, zIndex: total - offset } : { zIndex: total - offset }}
      initial={false}
      animate={{
        scale: 1 - offset * 0.04,
        y: offset * 16,
        opacity: offset > 2 ? 0 : 1,
      }}
      exit={{
        x: exitDirection === 1 ? -560 : 560,
        rotate: exitDirection === 1 ? -16 : 16,
        opacity: 0,
        scale: 0.97,
        transition: { duration: 0.42, ease: [0.22, 1, 0.36, 1] },
      }}
      transition={{ type: "spring", stiffness: 190, damping: 30, mass: 0.9 }}
      drag={isTop ? "x" : false}
      dragElastic={0.42}
      dragSnapToOrigin
      onDragEnd={isTop ? handleDragEnd : undefined}
    >
      <div className="h-full w-full bg-white rounded-[24px] border border-[#ececec] shadow-[0_24px_70px_rgba(0,0,0,0.28)] px-7 pt-7 pb-6 overflow-hidden cursor-grab active:cursor-grabbing">
        {section.render()}
      </div>
    </motion.div>
  );
}

export function DailyBriefStack({ open, onOpenChange }: { open: boolean; onOpenChange: (o: boolean) => void }) {
  const [index, setIndex] = useState(0);
  const total = SECTIONS.length;

  const handleSwipe = (dir: 1 | -1) => {
    setIndex((i) => {
      const next = i + dir;
      if (next < 0 || next >= total) return i;
      return next;
    });
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        onOpenChange(o);
        if (!o) setTimeout(() => setIndex(0), 250);
      }}
    >
      <DialogContent className="max-w-[440px] p-0 bg-transparent border-0 shadow-none [&>button]:hidden">
        <div className="relative h-[620px] w-full select-none">
          <AnimatePresence initial={false}>
            {SECTIONS.map((section, i) => {
              if (i < index || i > index + 2) return null;
              return (
                <SwipeCard
                  key={i}
                  section={section}
                  offset={i - index}
                  isTop={i === index}
                  onSwipe={handleSwipe}
                  total={total}
                />
              );
            })}
          </AnimatePresence>
        </div>

        <div className="flex justify-center gap-1.5 mt-5">
          {SECTIONS.map((_, i) => (
            <button
              key={i}
              type="button"
              onClick={() => setIndex(i)}
              className={cn(
                "h-1.5 rounded-full transition-all",
                i === index ? "w-7 bg-white" : "w-1.5 bg-white/35 hover:bg-white/55"
              )}
              aria-label={`Go to ${SECTIONS[i].label}`}
            />
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}

const _styles = `
.db-eyebrow { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: #aaa; margin-bottom: 14px; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
.db-eyebrow span { color: #ddd; }
.db-greeting { font-family: var(--font-serif-display, 'Playfair Display', serif); font-size: 30px; font-weight: 400; line-height: 1.1; color: #111; margin-bottom: 10px; letter-spacing: -0.01em; }
.db-greeting--sm { font-size: 24px; }
.db-lede { font-size: 14px; font-weight: 300; color: #666; line-height: 1.6; margin-bottom: 22px; }
`;
if (typeof document !== "undefined" && !document.getElementById("db-stack-styles")) {
  const el = document.createElement("style");
  el.id = "db-stack-styles";
  el.textContent = _styles;
  document.head.appendChild(el);
}
