import type { Client } from "./types";

export const clients: Client[] = [
  {
    id: 1,
    name: "Eleanor Hartley",
    company: "Hartley Family Trust",
    email: "eleanor@hartleytrust.com",
    phone: "+1 (212) 555-0148",
    stage: "Negotiation",
    aum: 12_400_000,
    owner: { initials: "JH", name: "John Harwick" },
    lastContact: "2h ago",
    nextAction: "Send revised IPS",
    starred: true,
  },
  {
    id: 2,
    name: "Denis Marlow",
    company: "Marlow Holdings LLC",
    email: "denis@marlowhold.com",
    phone: "+1 (415) 555-0192",
    stage: "Proposal",
    aum: 8_750_000,
    owner: { initials: "OP", name: "Olivia Park" },
    lastContact: "Today",
    nextAction: "Schedule rebalance call",
  },
  {
    id: 3,
    name: "Sarah Beaumont",
    company: "Beaumont Capital",
    email: "sarah@beaumontcap.com",
    phone: "+1 (646) 555-0173",
    stage: "Qualified",
    aum: 5_200_000,
    owner: { initials: "ML", name: "Marcus Lee" },
    lastContact: "Yesterday",
    nextAction: "KYC follow-up",
  },
  {
    id: 4,
    name: "Raphael Castellanos",
    company: "Castellanos Ventures",
    email: "raph@castellanos.vc",
    phone: "+1 (305) 555-0119",
    stage: "Proposal",
    aum: 7_900_000,
    owner: { initials: "JH", name: "John Harwick" },
    lastContact: "3d ago",
    nextAction: "Review allocation memo",
  },
  {
    id: 5,
    name: "Aurelia Whitfield",
    company: "Whitfield Estate",
    email: "a.whitfield@wfield.com",
    phone: "+1 (212) 555-0211",
    stage: "Lead",
    aum: 3_100_000,
    owner: { initials: "RC", name: "Rina Cho" },
    lastContact: "5d ago",
    nextAction: "Send discovery deck",
    starred: true,
  },
  {
    id: 6,
    name: "Marcus Caldwell",
    company: "Caldwell Estate",
    email: "marcus@caldwell.co",
    phone: "+1 (617) 555-0162",
    stage: "Closed",
    aum: 4_650_000,
    owner: { initials: "OP", name: "Olivia Park" },
    lastContact: "1w ago",
    nextAction: "Annual review prep",
  },
  {
    id: 7,
    name: "Priya Iyer",
    company: "Sterling Holdings",
    email: "priya@sterlingco.com",
    phone: "+1 (212) 555-0144",
    stage: "Negotiation",
    aum: 9_300_000,
    owner: { initials: "DM", name: "David Mensah" },
    lastContact: "4h ago",
    nextAction: "Lock advisory terms",
  },
  {
    id: 8,
    name: "Theodore Beck",
    company: "Beck & Sons",
    email: "ted@becksons.com",
    phone: "+1 (713) 555-0188",
    stage: "Lead",
    aum: 1_800_000,
    owner: { initials: "ML", name: "Marcus Lee" },
    lastContact: "2w ago",
    nextAction: "Re-engage via email",
  },
  {
    id: 9,
    name: "Isabelle Renault",
    company: "Renault Trust",
    email: "isabelle@renaulttrust.fr",
    phone: "+33 1 55 55 0177",
    stage: "Qualified",
    aum: 6_400_000,
    owner: { initials: "RC", name: "Rina Cho" },
    lastContact: "Today",
    nextAction: "Send proposal draft",
  },
  {
    id: 10,
    name: "Owen Fitzgerald",
    company: "Fitzgerald Capital",
    email: "owen@fitzcap.com",
    phone: "+1 (415) 555-0136",
    stage: "Proposal",
    aum: 11_200_000,
    owner: { initials: "JH", name: "John Harwick" },
    lastContact: "1h ago",
    nextAction: "Approve IPS revisions",
  },
];
